CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE data_sources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_organisation text NOT NULL,
  source_url text, dataset_version text, collection_date date, import_date timestamptz NOT NULL DEFAULT now(),
  geographic_resolution text, update_frequency text, licence_or_access_restrictions text,
  confidence_level text CHECK (confidence_level IN ('low','medium','high')), last_verification_date date,
  adapter_type text NOT NULL, is_synthetic boolean NOT NULL DEFAULT false
);
CREATE TABLE states (id bigserial PRIMARY KEY, lgd_code text UNIQUE NOT NULL, name text NOT NULL, geom geometry(MultiPolygon,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE districts (id bigserial PRIMARY KEY, state_id bigint REFERENCES states, lgd_code text UNIQUE NOT NULL, name text NOT NULL, active_hazards text[] NOT NULL DEFAULT '{}', geom geometry(MultiPolygon,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE subdistricts (id bigserial PRIMARY KEY, district_id bigint REFERENCES districts, lgd_code text UNIQUE NOT NULL, name text NOT NULL, geom geometry(MultiPolygon,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE gram_panchayats (id bigserial PRIMARY KEY, subdistrict_id bigint REFERENCES subdistricts, lgd_code text UNIQUE NOT NULL, name text NOT NULL, geom geometry(MultiPolygon,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE villages (id bigserial PRIMARY KEY, gram_panchayat_id bigint REFERENCES gram_panchayats, lgd_code text UNIQUE NOT NULL, census_code text, historical_codes jsonb NOT NULL DEFAULT '[]', name text NOT NULL, population integer CHECK (population>=0), households integer CHECK (households>=0), geom geometry(MultiPolygon,4326), source_id uuid REFERENCES data_sources, last_verified_at timestamptz);
CREATE TABLE habitations (id bigserial PRIMARY KEY, village_id bigint REFERENCES villages, code text UNIQUE, name text NOT NULL, population integer CHECK (population>=0), geom geometry(Point,4326), source_id uuid REFERENCES data_sources, last_verified_at timestamptz);
CREATE TABLE households (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), habitation_id bigint REFERENCES habitations, household_reference text UNIQUE NOT NULL, household_size smallint CHECK (household_size>0), restricted_payload jsonb, consent_status text, retention_until date, source_id uuid REFERENCES data_sources, created_at timestamptz DEFAULT now());
CREATE TABLE people_vulnerability_summary (id bigserial PRIMARY KEY, village_id bigint REFERENCES villages, children integer DEFAULT 0, elderly integer DEFAULT 0, pregnant_women integer DEFAULT 0, persons_with_disabilities integer DEFAULT 0, bedridden integer DEFAULT 0, sc_population integer DEFAULT 0, st_population integer DEFAULT 0, source_id uuid REFERENCES data_sources, valid_on date);
CREATE TABLE hazard_layers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), district_id bigint REFERENCES districts, hazard_type text NOT NULL, official_classification text, dataset_uri text, geom geometry(Geometry,4326), raster_reference text, source_id uuid REFERENCES data_sources, is_active boolean DEFAULT true);
CREATE TABLE hazard_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hazard_type text NOT NULL, external_id text, issue_time timestamptz, validity_start timestamptz, validity_end timestamptz, affected_area geometry(Geometry,4326), original_alert jsonb NOT NULL, processed_alert jsonb NOT NULL, source_id uuid REFERENCES data_sources, CHECK (validity_end IS NULL OR validity_end >= validity_start));
CREATE TABLE village_hazard_scores (id bigserial PRIMARY KEY, village_id bigint REFERENCES villages, hazard_type text NOT NULL, hazard_score numeric(5,2), exposure_score numeric(5,2), vulnerability_score numeric(5,2), access_weakness_score numeric(5,2), combined_score numeric(5,2), class text, explanation jsonb NOT NULL, threshold_config jsonb, confidence numeric(5,2), source_id uuid REFERENCES data_sources, calculated_at timestamptz DEFAULT now());
CREATE TABLE infrastructure (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), district_id bigint REFERENCES districts, type text NOT NULL, name text NOT NULL, capacity integer, status text, geom geometry(Point,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE roads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text, road_class text, length_km numeric, geom geometry(MultiLineString,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE road_status (id bigserial PRIMARY KEY, road_id uuid REFERENCES roads, status text NOT NULL, hazard_event_id uuid REFERENCES hazard_events, verified boolean DEFAULT false, observed_at timestamptz, source_id uuid REFERENCES data_sources);
CREATE TABLE shelters (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), infrastructure_id uuid REFERENCES infrastructure, verified_capacity integer, current_occupancy integer DEFAULT 0, hazard_safe boolean, last_inspected date, source_id uuid REFERENCES data_sources);
CREATE TABLE candidate_relocation_sites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), district_id bigint REFERENCES districts, name text NOT NULL, total_area_ha numeric, legally_available_area_ha numeric, buildable_area_ha numeric, excluded_area_ha numeric, land_verification_status text NOT NULL, owner_type text, geom geometry(Polygon,4326), source_id uuid REFERENCES data_sources);
CREATE TABLE carrying_capacity_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), site_id uuid REFERENCES candidate_relocation_sites, housing integer, water integer, sanitation integer, health integer, school integer, road_access integer, effective_capacity integer NOT NULL, current_population integer DEFAULT 0, allocated_relocatees integer DEFAULT 0, available_capacity integer NOT NULL, limiting_factor text NOT NULL, details jsonb, calculated_at timestamptz DEFAULT now());
CREATE TABLE household_surveys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid REFERENCES households, village_id bigint REFERENCES villages, gps geometry(Point,4326), vulnerability_counts jsonb, house_type text, house_condition text, visible_damage text, flood_depth_cm numeric, observed_danger text, access_status text, needs jsonb, nearest_shelter_id uuid REFERENCES shelters, photo_reference text, survey_timestamp timestamptz, surveyor_id text, verification_status text DEFAULT 'pending', consent_acknowledged boolean NOT NULL, source_id uuid REFERENCES data_sources);
CREATE TABLE relocation_priority_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid REFERENCES households, habitation_id bigint REFERENCES habitations, static_risk numeric(5,2), active_warning numeric(5,2), observed_danger numeric(5,2), household_vulnerability numeric(5,2), building_weakness numeric(5,2), isolation numeric(5,2), priority_score numeric(5,2), priority_class text, explanation jsonb NOT NULL, verification_status text DEFAULT 'pending', calculated_at timestamptz DEFAULT now());
CREATE TABLE alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), hazard_event_id uuid REFERENCES hazard_events, title text NOT NULL, severity text, issue_time timestamptz, valid_until timestamptz, affected_area geometry(Geometry,4326), original_alert jsonb, processed_alert jsonb, source_id uuid REFERENCES data_sources);
CREATE TABLE data_import_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid REFERENCES data_sources, filename text, format text, status text NOT NULL, preview jsonb, validation_errors jsonb, duplicate_count integer DEFAULT 0, rollback_token uuid DEFAULT gen_random_uuid(), imported_by text, created_at timestamptz DEFAULT now(), completed_at timestamptz);
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, actor_id text NOT NULL, actor_role text NOT NULL, action text NOT NULL, entity_type text, entity_id text, before_state jsonb, after_state jsonb, ip_hash text, created_at timestamptz DEFAULT now());
CREATE INDEX villages_geom_gix ON villages USING gist(geom); CREATE INDEX hazard_layers_geom_gix ON hazard_layers USING gist(geom); CREATE INDEX roads_geom_gix ON roads USING gist(geom); CREATE INDEX alerts_active_idx ON alerts(valid_until) WHERE valid_until IS NOT NULL;
